steps:
  - label: Terraform deploy
    command: ".buildkite/deploy.sh"
    plugins:
      - docker-compose#v3.0.3:
          run: app
          env:
            - AWS_DEFAULT_REGION
            - AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY
